### ISSUE TITLE
Issue with Elvui 6.08 I dont see anything

### ISSUE THREAD

**Issue by Cortes-Jeremy** [wotlk-addons/DiminishingReturns#1]
Hi, in the support status /drstatus it say that ElvUI is supported and loaded, but I cant see anything, in the config (/dr) it only show blizzard frame in the scroll selection.

Using ElvUI 6.08 (latest)
Without ElvUI frame are showing near blizzard frame (player, target, focus) when enabling ElvUI, nothing show.

Tested with fresh wow 3.3.5 installation (no saved variables)

**Comment by vendethiel** [comment]
Hey,

I admit I never used elvui-wotlk.
Just to make sure, what elvui-wotlk are you using? If you could provide a DL link that’d be helpful.

**Comment by Cortes-Jeremy** [comment]
Hi, 
thank's you for your time.

I use this one: https://github.com/ElvUI-WotLK/ElvUI
base ElvUI + ElvUI_OptionsUI on fresh installation without anything else enabled (no other addons or elvui plugin).

**Comment by vendethiel** [comment]
Seems like a load order issue. Will try to find a solution.

**Comment by Cortes-Jeremy** [comment]
Thank you, your help are really appreciated !

**Comment by vendethiel** [comment]
OK, finally got around to it.
Please try this new version.
NOTE: you _will_ have to toy with the options to show it where you want, by default, I think it shows "below" the ElvUI frame.
But by changing the DR to show on the top right, and enabling the test mode, I was able to see it on my ElvUI target.

**Comment by Cortes-Jeremy** [comment]
Hey Vendethiel,

The addon work well with ElvUI now !
I have add "player" support on line 18 and 28. Worked great !
It's perfect now, Thank you for your time !

**Comment by vendethiel** [comment]
No problem, glad to know it works :)
